### ISSUE TITLE
使用env而不是dns？

### ISSUE THREAD

**Issue by eagleyinfz** [rootsongjc/k8s-app-monitor-agent#1]
以下配置与实现是不是意味着使用env而非dns？

**k8s-app-monitor-agent/manifest.yaml**
spec. env: 
        - name: APP_PORT
          value: "3000"
        - name: SERVICE_NAME
          value: "k8s-app-monitor-test"

**k8s-app-monitor-agent/main.go**
port := os.Getenv("APP_PORT")
	service := os.Getenv("SERVICE_NAME")
	if len(port) == 0 {
		port = "3000"
	}
	if len(service) == 0 {
		service = "localhost"
	}
	resp, err := http.Get("http://" + service + ":" + port + "/metrics")

**Comment by rootsongjc** [comment]
不是的，请注意这一行：
```
resp, err := http.Get("http://" + service + ":" + port + "/metrics")
```
实际上这个http请求就是通过DNS的，这里传入的service就是服务名称，我所说的使用env指的是使用Pod内部kuberentes自动注入的env，比如获取该环境变量`K8S_APP_MONITOR_TEST_PORT`就可以只记得得到该service的地址而无需通过DNS。

**Comment by eagleyinfz** [comment]
明白，谢谢解答
